spring:
  application:
    name: gateway-service  
  cloud:
    gateway:
      routes:
      - id: personas
        uri: http://localhost:8081/
        predicates:
        - Path=/personas/**
      - id: tipodirecciones
        uri: http://localhost:8071/
        predicates:
        - Path=/tipodirecciones/**
      - id: tipodirecciones
        uri: http://localhost:8072/
        predicates:
        - Path=/tipodirecciones/**
      - id: tipodirecciones
        uri: http://localhost:8073/
        predicates:
        - Path=/tipodirecciones/**
        
server:
  port: 8091
